Fixing bug for addUserRecord
awslabs/amazon-kinesis-producer pull request #554
Opened 2024-01-03 19:17 UTC by aakkem

*Issue #, if available:*
Support for CAA

*Description of changes:*

Adding the implementation for addUserRecord 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-03 19:22 UTC, shanmsac requested changes
minor comments

2024-01-03 19:22 UTC, shanmsac commented on java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java
> +     *            Binary data of the record. Maximum size 1MiB.
Add @param for `schema` parameter

2024-01-03 19:22 UTC, shanmsac commented on java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java
> +    }
new line

2024-01-03 19:22 UTC, shanmsac commented on java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/UserRecord.java
> +    }
new line

2024-01-03 19:22 UTC, shanmsac commented on java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java
>      public ListenableFuture<UserRecordResult> addUserRecord(String stream, String partitionKey, String explicitHashKey, ByteBuffer data, String streamARN, Schema schema) {
Please add Javadoc comment for this function with all parameters in order

2024-01-03 19:43 UTC, aakkem commented on java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducer.java
> +     *            Binary data of the record. Maximum size 1MiB.
Addressed the comments.

2024-01-03 20:52 UTC, shanmsac approved these changes
lgtm

2024-01-03 21:36 UTC, merged

2024-01-09 16:51 UTC, kabennett commented
When are you going to make the 0.15.10 release available in Maven Central?

2024-01-10 23:20 UTC, aakkem commented
This should be available by the end of the week.

2024-01-11 00:37 UTC, kabennett commented
Thanks. Do you know if this release will fix the errors I am encountering as documented in stackoverflow [here](https://stackoverflow.com/questions/77788780/kpl-errors-encountered-after-upgrading-spring-cloud-stream-binder-for-kinesis-to)?

2024-01-16 22:10 UTC, kabennett commented
Hey, @aakkem, are you going to release 0.15.10 to Maven Central?

2024-01-30 12:38 UTC, ofeki-neosec commented
Hey @aakkem, is there an estimation on when this will be released to Maven Central?

2024-01-30 15:52 UTC, kabennett commented
@ofeki-neosec take a look at[ this stackoverflow link](https://stackoverflow.com/questions/77788780/kpl-errors-encountered-after-upgrading-spring-cloud-stream-binder-for-kinesis-to) I posted a few weeks ago. I updated that post with a comment you may find helpful. Are you having the same issue?

2024-01-30 20:51 UTC, joshuabaird commented
I believe this bug is also causing segfaults when using IRSA with EKS to provide credentials.  Reverting to v0.15.8 fixes the issue.  See https://github.com/awslabs/amazon-kinesis-producer/issues/558 for details.

2024-02-06 09:26 UTC, svenwilliger commented
@aakkem could you please release it to Maven Central now ?